version: "3.9"

services:

  cas:
    container_name: 'maap-auth-cas'
    build:
      dockerfile: Dockerfile
      context: ./cas
    image: 'casDockerImage'
    volumes:
      - cas-logs:/tmp/logs
    ports:
      - 11009:11009
    restart: on-failure

volumes:
  cas-logs:

    
